export const locationsList = [
    {
        region: "Ontario",
        locations: [
            { name: "Ancaster", link: "/ontario/ancaster" },
            { name: "Arnprior", link: "/ontario/arnprior" },
            { name: "Barrie", link: "/ontario/barrie" },
            { name: "Belleville", link: "/ontario/belleville" },
            { name: "Brantford", link: "/ontario/brantford" },
            { name: "Brockville", link: "/ontario/brockville" },
            { name: "Burlington", link: "/ontario/burlington" },
            { name: "Cambridge", link: "/ontario/cambridge" },
            { name: "Carleton Place", link: "/ontario/carleton-place" },
            { name: "Casselman", link: "/ontario/casselman" },
            { name: "Chatham", link: "/ontario/chatham" },
            { name: "Clarington", link: "/ontario/clarington" },
            { name: "Cornwall", link: "/ontario/cornwall" },
            { name: "Danforth", link: "/ontario/danforth" },
            { name: "East York", link: "/ontario/east-york" },
            { name: "Essex", link: "/ontario/essex" },
            { name: "Etobicoke", link: "/ontario/etobicoke" },
            { name: "Georgetown", link: "/ontario/georgetown" },
            { name: "Georgian Bay", link: "/ontario/georgian-bay" },
            { name: "Guelph", link: "/ontario/guelph" },
            { name: "Hamilton", link: "/ontario/hamilton" },
            { name: "Hawkesbury", link: "/ontario/hawkesbury" },
            { name: "Kawartha Lakes", link: "/ontario/kawartha-lakes" },
            { name: "Kemptville", link: "/ontario/kemptville" },
            { name: "Kingston", link: "/ontario/kingston" },
            { name: "Kitchener", link: "/ontario/kitchener" },
            { name: "Lindsay", link: "/ontario/lindsay" },
            { name: "London", link: "/ontario/london" },
            { name: "Markham", link: "/ontario/markham" },
            { name: "Milton", link: "/ontario/milton" },
            { name: "Mississauga", link: "/ontario/mississauga" },
            { name: "Newmarket", link: "/ontario/newmarket" },
            { name: "North Bay", link: "/ontario/north-bay" },
            { name: "North York", link: "/ontario/north-york" },
            { name: "Oakville", link: "/ontario/oakville" },
            { name: "Orillia", link: "/ontario/orillia" },
            { name: "Oshawa", link: "/ontario/oshawa" },
            { name: "Ottawa", link: "/ontario/ottawa" },
            { name: "Oxford County", link: "/ontario/oxford-county" },
            { name: "Packenham", link: "/ontario/packenham" },
            { name: "Parry Sound", link: "/ontario/parry-sound" },
            { name: "Perth", link: "/ontario/perth" },
            { name: "Peterborough", link: "/ontario/peterborough" },
            { name: "Pickering", link: "/ontario/pickering" },
            { name: "Renfrew", link: "/ontario/renfrew" },
            { name: "Rexdale", link: "/ontario/rexdale" },
            { name: "Richmond Hill", link: "/ontario/richmond-hill" },
            { name: "Richmond Hill South", link: "/ontario/richmond-hill-south" },
            { name: "Rural Eastern Ontario", link: "/ontario/rural-eastern-ontario" },
            { name: "Russell", link: "/ontario/russell" },
            { name: "Sarnia", link: "/ontario/sarnia" },
            { name: "Scarborough", link: "/ontario/scarborough" },
            { name: "Smith Falls", link: "/ontario/smith-falls" },
            { name: "Toronto Beaches", link: "/ontario/toronto-beaches" },
            { name: "Thunder Bay", link: "/ontario/thunder-bay" },
            { name: "Timmins", link: "/ontario/timmins" },
            { name: "Toronto Downtown", link: "/ontario/toronto-downtown" },
            { name: "Tweed", link: "/ontario/tweed" },
            { name: "Uxbridge", link: "/ontario/uxbridge" },
            { name: "Vaughan", link: "/ontario/vaughan" },
            { name: "Walkerton", link: "/ontario/walkerton" },
            { name: "Waterloo", link: "/ontario/waterloo" },
            { name: "Whitby", link: "/ontario/whitby" },
            { name: "Windsor", link: "/ontario/windsor" },
            { name: "Woodstock", link: "/ontario/woodstock" },
            { name: "Yorkdale", link: "/ontario/yorkdale" },
        ],
    },
];  